### ISSUE TITLE
How to change padding for the drop down list items?

### ISSUE THREAD

**Issue by chaisangam** [basvandenberg/ng-select#221]

**Comment by basvandenberg** [comment]
```css
ng-select select-dropdown>div .options ul li {
    padding: 8px 12px;
}
```
