### ISSUE TITLE
Integrating in Bootstrap input group

### ISSUE THREAD

**Issue by Disane87** [basvandenberg/ng-select#306]
Hey there, I really like your project! Actually we are going to integrate it in out application but we have some problems in putting your select within an input-group of bootstrap. Your select is always a fixed height (as we saw 30px). So it doesn't fit properly within the group:

![image](https://user-images.githubusercontent.com/956158/41917139-f58e8aac-7959-11e8-82e2-2ce077b5dfce.png)

As you can see, the height of the input group isn't applied, the border is also not applied.

For reproduction I've set up an example at stackblitz:
https://stackblitz.com/edit/angular-ng-bootstrap-ng-select

**Comment by basvandenberg** [comment]
You can override the component styling, for example by adding the following to the styles.css in you stackblitz example:

```css
my-app ng-select>div {
  border: 1px solid #eee;
  border-radius: 0.25rem 0 0 0.25rem;
}
my-app ng-select>div>div.single {
  height: 36px;
}
my-app ng-select>div>div.single>div.value {
  line-height: 36px;
}
my-app ng-select>div>div.single>div.toggle {
  line-height: 36px;
}
```
